export default {
  namespaced: true,
  state: {
    truckersData: {
      rankName: 'Garbage reel',
      level: 3,
      currentExp: 320,
      requiredExp: 350,
      trucks: [
        {
          id: 0,
          name: 'trash2',
          rentCost: 1480,
          available: true,
          availableLevel: 3,
          reward: 30,
          payment: 100,
        },
        {
          id: 1,
          name: 'tiptruck',
          rentCost: 2910,
          available: true,
          availableLevel: 5,
          reward: 30,
          payment: 100,
        },
        {
          id: 2,
          name: 'mixer2',
          rentCost: 2370,
          available: true,
          availableLevel: 4,
          payment: 100,
        },
        {
          id: 3,
          name: 'mule',
          rentCost: 900,
          available: true,
          availableLevel: 2,
          reward: 30,
          payment: 100,
        },
        {
          id: 4,
          name: 'mule2',
          rentCost: 230,
          available: true,
          availableLevel: 1,
          reward: 30,
          payment: 100,
        },
        {
          id: 5,
          name: 'mule3',
          rentCost: 800,
          available: true,
          availableLevel: 2,
          reward: 30,
          payment: 100,
        },
        {
          id: 6,
          name: 'mule4',
          rentCost: 100,
          available: true,
          availableLevel: 1,
          reward: 30,
          payment: 100,
        },
        {
          id: 7,
          name: 'benson',
          rentCost: 1050,
          available: true,
          availableLevel: 2,
          reward: 30,
          payment: 100,
        },
        {
          id: 8,
          name: 'pounder2',
          rentCost: 4000,
          available: false,
          availableLevel: 11,
          payment: 100,
        },
        {
          id: 9,
          name: 'truck 123',
          rentCost: 200,
          available: true,
          availableLevel: 1,
          reward: 30,
          payment: 100,
        },
        {
          id: 10,
          name: 'truck 999',
          rentCost: 1000,
          available: true,
          availableLevel: 2,
          reward: 30,
          payment: 100,
        },
        {
          id: 11,
          name: 'truck 9000',
          rentCost: 2000,
          available: true,
          availableLevel: 3,
          reward: 30,
          payment: 100,
        },
        {
          id: 12,
          name: 'truck 3000',
          rentCost: 9000,
          available: false,
          availableLevel: 9,
          reward: 30,
          payment: 100,
        },
      ],
    },
  },
  mutations: {
    setData: function(state, truckData) {
      state.truckersData = truckData
    },
  },
}