// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whistler.EFCore;

namespace Whistler.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20211102152115_AddResourcesToPriceMenu")]
    partial class AddResourcesToPriceMenu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Whistler.MoneySystem.Models.CheckingAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<int>("UUID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("efcore_bank_account");
                });

            modelBuilder.Entity("Whistler.MoneySystem.Models.CreditModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<bool>("ClosedCredit")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HistoryPayment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Indebtedness")
                        .HasColumnType("int");

                    b.Property<float>("InterestRate")
                        .HasColumnType("float");

                    b.Property<int>("LeftPayments")
                        .HasColumnType("int");

                    b.Property<int>("PayedAmount")
                        .HasColumnType("int");

                    b.Property<int>("Percents")
                        .HasColumnType("int");

                    b.Property<int>("PledgeId")
                        .HasColumnType("int");

                    b.Property<int>("PledgeType")
                        .HasColumnType("int");

                    b.Property<int>("TypePayment")
                        .HasColumnType("int");

                    b.Property<int>("UUID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("efcore_bank_credit");
                });

            modelBuilder.Entity("Whistler.MoneySystem.Models.Deposit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddedMoney")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<bool>("ClosedDeposit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DepositFullTime")
                        .HasColumnType("int");

                    b.Property<int>("DepositMoney")
                        .HasColumnType("int");

                    b.Property<int>("DepositTypes")
                        .HasColumnType("int");

                    b.Property<int>("HoursInInterval")
                        .HasColumnType("int");

                    b.Property<int>("Profit")
                        .HasColumnType("int");

                    b.Property<int>("UUID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("efcore_bank_deposit");
                });

            modelBuilder.Entity("Whistler.MoneySystem.Models.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<int>("FromType")
                        .HasColumnType("int");

                    b.Property<int>("Tax")
                        .HasColumnType("int");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.Property<int>("ToType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("efcore_bank_transact");
                });
#pragma warning restore 612, 618
        }
    }
}
