using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace Whistler.Core.Animations
{
    internal static class AnimationsConfig
    {
        static AnimationsConfig()
        {
			var animDict = new Dictionary<string, AnimationConfig>
			{
				["social_hand_up"] = new AnimationConfig("random@arrests@busted", "idle_c", 49, "social"),
				["social_write_down"] = new AnimationConfig("amb@medic@standing@timeofdeath@idle_a", "idle_a", 49, "social"),
				["social_like"] = new AnimationConfig("anim@mp_player_intselfiethumbs_up", "idle_a", 49, "social"),
				["social_salute"] = new AnimationConfig("anim@mp_player_intuppersalute", "idle_a", 49, "social"),
				["social_hands_around_head"] = new AnimationConfig("anim@mp_player_intupperyou_loco", "idle_a", 49, "social"),
				["social_king_salute"] = new AnimationConfig("anim@mp_player_intupperwave", "idle_a", 49, "social"),
				["social_flex"] = new AnimationConfig("anim@mp_player_intupperv_sign", "idle_a", 49, "social"),
				["social_double_like"] = new AnimationConfig("anim@mp_player_intupperthumbs_up", "idle_a", 49, "social"),
				["social_startle"] = new AnimationConfig("anim@mp_player_intupperthumb_on_ears", "idle_a", 49, "social"),
				["social_surrender"] = new AnimationConfig("anim@mp_player_intuppersurrender", "idle_a", 49, "social"),
				["social_slow_clap"] = new AnimationConfig("anim@mp_player_intupperslow_clap", "idle_a", 49, "social"),
				["social_peace"] = new AnimationConfig("anim@mp_player_intupperpeace", "idle_a", 49, "social"),
				["social_no_way"] = new AnimationConfig("anim@mp_player_intupperno_way", "idle_a", 49, "social"),
				["social_jazz_hands"] = new AnimationConfig("anim@mp_player_intupperjazz_hands", "idle_a", 49, "social"),
				["social_fish"] = new AnimationConfig("anim@mp_player_intupperfind_the_fish", "idle_a", 49, "social"),
				["social_face_palm"] = new AnimationConfig("anim@mp_player_intupperface_palm", "idle_a", 49, "social"),
				["social_chicken_taunt"] = new AnimationConfig("anim@mp_player_intupperchicken_taunt", "idle_a", 49, "social"),
				["social_ok"] = new AnimationConfig("anim@mp_player_intselfiedock", "idle_a", 49, "social"),
				["social_over_here"] = new AnimationConfig("friends@frf@ig_1", "over_here_idle_b", 49, "social"),
				["social_rock"] = new AnimationConfig("mp_player_int_upperrock", "mp_player_int_rock", 49, "social"),
				["social_peace_all"] = new AnimationConfig("mp_player_int_upperpeace_sign", "mp_player_int_peace_sign", 49, "social"),
				["social_blow_kiss"] = new AnimationConfig("anim@mp_player_intcelebrationmale@blow_kiss", "blow_kiss", 39, "social"),
				["social_blow_kiss_2"] = new AnimationConfig("anim@mp_player_intselfieblow_kiss", "exit", 49, "social"),
				["social_hooker"] = new AnimationConfig("mini@hookers_spvanilla", "idle_d", 39, "social"),
				["social_ass"] = new AnimationConfig("anim@mp_freemode_return@f@idle", "idle_a", 49, "social"),
				["social_mind_blown"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@mind_blown", "mind_blown", 39, "social"),
				["social_peace_1"] = new AnimationConfig("anim@mp_player_intincarpeacebodhi@ds@", "idle_a", 49, "social"),
				["social_peace_2"] = new AnimationConfig("anim@mp_player_intincarpeacebodhi@ps@", "idle_a_fp", 49, "social"),
				["social_rock_1"] = new AnimationConfig("anim@mp_player_intincarrockbodhi@ds@", "idle_a", 49, "social"),
				["social_no_head"] = new AnimationConfig("gestures@m@car@van@casual@ps", "gesture_head_no", 49, "social"),
				["social_no_head_hand"] = new AnimationConfig("gestures@m@car@van@casual@ps", "gesture_nod_no_hard", 49, "social"),
				["social_no_finger"] = new AnimationConfig("anim@mp_player_intupperno_way", "idle_a_fp", 49, "social"),
				["social_reject_1"] = new AnimationConfig("anim@heists@ornate_bank@chat_manager", "fail", 49, "social"),
				["social_reject_2"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@no_way", "no_way", 39, "social"),
				["social_ok_hand"] = new AnimationConfig("anim@mp_player_intincarthumbs_upstd@rps@", "idle_a", 49, "social"),
				["social_ok_hands"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@thumbs_up", "thumbs_up", 49, "social"),
				["social_to_me"] = new AnimationConfig("missfam4", "say_hurry_up_a_trevor", 39, "social"),
				["social_photograph"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@photography", "photography", 39, "social"),
				["social_smoke_1"] = new AnimationConfig("amb@code_human_in_car_mp_actions@first_person@smoke@std@ds@base", "idle_a", 49, "social"),
				["social_smoke_2"] = new AnimationConfig("amb@world_human_aa_smoke@male@idle_a", "idle_a", 39, "social"),
				["social_money_rain"] = new AnimationConfig("anim@arena@celeb@flat@solo@props@", "make_it_rain_b_player_b", 39, "social"),
				["social_happy_1"] = new AnimationConfig("anim@arena@celeb@flat@solo@no_props@", "angry_clap_a_player_a", 39, "social"),
				["social_happy_2"] = new AnimationConfig("anim@arena@celeb@flat@solo@no_props@", "angry_clap_b_player_a", 39, "social"),
				["social_happy_3"] = new AnimationConfig("anim@arena@celeb@flat@solo@no_props@", "angry_clap_b_player_b", 39, "social"),
				["social_happy_4"] = new AnimationConfig("anim@arena@celeb@flat@solo@no_props@", "cap_a_player_a", 39, "social"),
				["social_happy_5"] = new AnimationConfig("anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a", 39, "social"),
				["social_happy_6"] = new AnimationConfig("anim@arena@celeb@flat@solo@no_props@", "slide_a_player_a", 39, "social"),
				["social_happy_7"] = new AnimationConfig("missmic_4premiere", "movie_prem_02_f_b", 39, "social"),
				["social_guitar"] = new AnimationConfig("anim@mp_player_intcelebrationmale@air_guitar", "air_guitar", 39, "social"),
				["social_clap"] = new AnimationConfig("anim@mp_player_intincarslow_clapbodhi@ds@", "idle_a", 49, "social"),
				["social_cheer"] = new AnimationConfig("amb@world_human_cheering@male_a", "base", 39, "social"),
				["social_facepalm"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@face_palm", "face_palm", 39, "social"),
				["social_praise_1"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@finger_kiss", "finger_kiss", 39, "social"),
				["social_praise_2"] = new AnimationConfig("anim@mp_player_intincarfinger_kissbodhi@ds@", "exit_fp", 49, "social"),

				["phis_yoga_female"] = new AnimationConfig("amb@world_human_yoga@female@base", "base_a", 39, "phis"),
				["phis_yoga_male"] = new AnimationConfig("amb@world_human_yoga@male@base", "base_b", 39, "phis"),
				["phis_sit_ups"] = new AnimationConfig("amb@world_human_sit_ups@male@base", "base", 39, "phis"),
				["phis_push_ups"] = new AnimationConfig("amb@world_human_push_ups@male@base", "base", 39, "phis"),
				["phis_meditiate"] = new AnimationConfig("rcmcollect_paperleadinout@", "meditiate_idle", 39, "phis"),
				["phis_jogging"] = new AnimationConfig("amb@world_human_jog_standing@male@base", "base", 39, "phis"),
				["phis_box"] = new AnimationConfig("anim@mp_player_intuppershadow_boxing", "idle_a", 39, "phis"),
				["phis_box_2"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@shadow_boxing", "shadow_boxing", 39, "phis"),
				["phis_karate"] = new AnimationConfig("anim@mp_player_intupperkarate_chops", "idle_a", 39, "phis"),
				["phis_karate_2"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@karate_chops", "karate_chops", 39, "phis"),
				["phis_yoga_2"] = new AnimationConfig("missfam5_yoga", "a2_fail_to_start", 39, "phis"),
				["phis_yoga"] = new AnimationConfig("missfam5_yoga", "a2_fail_to_start", 39, "phis"),

				["indecent_middle_finger"] = new AnimationConfig("anim@mp_player_intselfiethe_bird", "idle_a", 49, "indecent"),
				["indecent_something_else"] = new AnimationConfig("anim@mp_player_intincardockstd@ps@", "idle_a", 49, "indecent"),
				["indecent_nose_pick"] = new AnimationConfig("anim@mp_player_intuppernose_pick", "idle_a", 49, "indecent"),
				["indecent_middle_finger_all_1"] = new AnimationConfig("anim@mp_player_intupperfinger", "idle_a", 49, "indecent"),
				["indecent_middle_finger_1"] = new AnimationConfig("mp_player_intfinger", "mp_player_int_finger", 39, "indecent"),
				["indecent_sex_male"] = new AnimationConfig("rcmpaparazzo_2", "shag_action_a", 39, "indecent"),
				["indecent_sex_female"] = new AnimationConfig("rcmpaparazzo_2", "shag_action_poppy", 39, "indecent"),
				["indecent_sex_male_2"] = new AnimationConfig("rcmpaparazzo_2", "shag_loop_a", 39, "indecent"),
				["indecent_sex_female_2"] = new AnimationConfig("rcmpaparazzo_2", "shag_loop_poppy", 39, "indecent"),
				["indecent_air_sex"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@air_shagging", "air_shagging", 39, "indecent"),
				["indecent_air_kiss"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@blow_kiss", "blow_kiss", 39, "indecent"),
				["indecent_kiss_male"] = new AnimationConfig("mp_ped_interaction", "kisses_guy_a", 39, "indecent"),
				["indecent_kiss_female"] = new AnimationConfig("mp_ped_interaction", "kisses_guy_b", 39, "indecent"),
				["indecent_you_loco"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@you_loco", "you_loco", 39, "indecent"),
				["indecent_middle_finger_all_2"] = new AnimationConfig("anim@arena@celeb@flat@paired@no_props@", "laugh_b_player_b", 39, "indecent"),
				["indecent_middle_finger_all_3"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@finger", "finger", 39, "indecent"),
				["indecent_cry_baby"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@cry_baby", "cry_baby", 39, "indecent"),
				["indecent_cut_throat"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@cut_throat", "cut_throat", 39, "indecent"),
				["indecent_stinker_1"] = new AnimationConfig("anim@mp_player_intupperstinker", "idle_a", 39, "indecent"),
				["indecent_stinker_2"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@stinker", "stinker", 39, "indecent"),
				["indecent_nose_pick_2"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@nose_pick", "nose_pick", 39, "indecent"),
				["indecent_knuckle_crunch"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@knuckle_crunch", "knuckle_crunch", 39, "indecent"),
				["indecent_idiot_1"] = new AnimationConfig("anim@mp_player_intincaryou_locobodhi@ds@", "idle_a", 49, "indecent"),
				["indecent_sex_with_hands"] = new AnimationConfig("anim@mp_player_intcelebrationfemale@dock", "dock", 39, "indecent"),
				["indecent_finger_down"] = new AnimationConfig("anim@arena@celeb@flat@solo@no_props@", "thumbs_down_a_player_a", 49, "indecent"),
				["indecent_chicken"] = new AnimationConfig("anim@mp_player_intcelebrationmale@chicken_taunt", "chicken_taunt", 39, "indecent"),
				["indecent_goat_1"] = new AnimationConfig("anim@mp_player_intincarthumb_on_earsbodhi@ds@", "idle_a", 49, "indecent"),
				["indecent_goat_2"] = new AnimationConfig("anim@mp_player_intincarthumb_on_earsstd@rds@", "idle_a", 49, "indecent"),
				["indecent_wank_1"] = new AnimationConfig("anim@mp_player_intincarwanklow@ps@", "idle_a", 49, "indecent"),
				["indecent_wank_2"] = new AnimationConfig("anim@mp_player_intincarwankstd@ps@", "idle_a", 49, "indecent"),

				["stay_hands_on_belt"] = new AnimationConfig("amb@world_human_cop_idles@male@base", "base", 39, "stay"),
				["stay_knuckle_crunch"] = new AnimationConfig("anim@mp_player_intupperknuckle_crunch", "idle_a", 49, "stay"),
				["stay_fold_arms"] = new AnimationConfig("anim@amb@nightclub@peds@", "rcmme_amanda1_stand_loop_cop", 39, "stay"),
				["stay_go_away"] = new AnimationConfig("anim@amb@nightclub@peds@", "mini_strip_club_idles_bouncer_go_away_go_away", 39, "stay"),
				["stay_stop"] = new AnimationConfig("anim@amb@nightclub@peds@", "mini_strip_club_idles_bouncer_stop_stop", 39, "stay"),
				["stay_biceps_1"] = new AnimationConfig("anim@amb@nightclub@peds@", "amb_world_human_muscle_flex_arms_in_front_base", 39, "stay"),
				["stay_biceps_2"] = new AnimationConfig("amb@world_human_muscle_flex@arms_at_side@base", "base", 39, "stay"),
				["stay_biceps_3"] = new AnimationConfig("amb@world_human_muscle_flex@arms_at_side@idle_a", "idle_a", 39, "stay"),
				["stay_biceps_4"] = new AnimationConfig("amb@world_human_muscle_flex@arms_at_side@idle_a", "idle_c", 39, "stay"),
				["stay_biceps_5"] = new AnimationConfig("amb@world_human_muscle_flex@arms_in_front@idle_a", "idle_b", 39, "stay"),
				["stay_biceps_6"] = new AnimationConfig("amb@world_human_muscle_flex@arms_in_front@idle_a", "idle_b", 39, "stay"),
				["stay_stand_near_wall"] = new AnimationConfig("amb@lo_res_idles@", "world_human_lean_male_foot_up_lo_res_base", 39, "stay"),
				["stay_stand_1"] = new AnimationConfig("amb@world_human_hang_out_street@female_hold_arm@base", "base", 39, "stay"),
				["stay_stand_2"] = new AnimationConfig("amb@world_human_prostitute@hooker@base", "base", 39, "stay"),
				["stay_stand_3"] = new AnimationConfig("ep_8_rcm-10", "a_m_y_epsilon_01^1-10", 39, "stay"),
				["stay_stand_4"] = new AnimationConfig("low_fun_mcs1-0", "mp_m_g_vagfun_01^10_dual-0", 39, "stay"),
				["stay_stand_5"] = new AnimationConfig("mini@hookers_spvanilla", "idle_reject_loop_a", 39, "stay"),
				["stay_stand_6"] = new AnimationConfig("mp_move@prostitute@f@cokehead", "idle", 39, "stay"),
				["stay_stand_7"] = new AnimationConfig("mp_move@prostitute@f@crackhead", "idle", 39, "stay"),
				["stay_stand_8"] = new AnimationConfig("mp_move@prostitute@f@french", "idle", 39, "stay"),
				["stay_drunk_2"] = new AnimationConfig("mp_sleep", "sleep_loop", 39, "stay"),
				["stay_plank"] = new AnimationConfig("amb@lo_res_idles@", "world_human_push_ups_lo_res_base", 39, "stay"),

				["dance_dance_1"] = new AnimationConfig("amb@world_human_partying@female@partying_beer@base", "base", 39, "dance"),
				["dance_dance_2"] = new AnimationConfig("amb@world_human_strip_watch_stand@male_a@idle_a", "idle_c", 39, "dance"),
				["dance_dance_3"] = new AnimationConfig("mini@strip_club@idles@dj@idle_04", "idle_04", 39, "dance"),
				["dance_dance_4"] = new AnimationConfig("mini@strip_club@lap_dance@ld_girl_a_song_a_p1", "ld_girl_a_song_a_p1_f", 39, "dance"),
				["dance_dance_5"] = new AnimationConfig("special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag", 39, "dance"),
				["dance_dance_6"] = new AnimationConfig("mini@strip_club@private_dance@part1", "priv_dance_p1", 39, "dance"),
				["dance_dance_7"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^1", 39, "dance"),
				["dance_dance_8"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^3", 39, "dance"),
				["dance_dance_9"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_male^2", 39, "dance"),
				["dance_dance_10"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_male^4", 39, "dance"),
				["dance_dance_11"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@", "hi_dance_crowd_09_v1_female^1", 39, "dance"),
				["dance_dance_12"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@", "hi_dance_crowd_09_v2_female^1", 39, "dance"),
				["dance_dance_13"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@", "hi_dance_crowd_09_v2_female^3", 39, "dance"),
				["dance_dance_14"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@", "hi_dance_crowd_11_v1_female^1", 39, "dance"),
				["dance_dance_15"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@", "hi_dance_crowd_13_v2_female^1", 39, "dance"),
				["dance_dance_16"] = new AnimationConfig("anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_17_crotchgrab_laz", 39, "dance"),
				["dance_dance_17"] = new AnimationConfig("anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_17_teapotthrust_laz", 39, "dance"),
				["dance_dance_18"] = new AnimationConfig("anim@amb@nightclub@lazlow@hi_railing@", "ambclub_09_mi_hi_bellydancer_laz", 39, "dance"),
				["dance_dance_19"] = new AnimationConfig("anim@amb@nightclub@lazlow@hi_railing@", "ambclub_10_mi_hi_crotchhold_laz", 39, "dance"),
				["dance_dance_20"] = new AnimationConfig("anim@amb@nightclub@lazlow@hi_railing@", "ambclub_12_mi_hi_bootyshake_laz", 39, "dance"),
				["dance_dance_21"] = new AnimationConfig("anim@amb@nightclub@lazlow@hi_railing@", "ambclub_13_mi_hi_sexualgriding_laz", 39, "dance"),
				["dance_dance_22"] = new AnimationConfig("anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "med_center", 39, "dance"),
				["dance_dance_23"] = new AnimationConfig("anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", "med_center", 39, "dance"),
				["dance_dance_24"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_male^5", 39, "dance"),
				["dance_dance_25"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_11_v1_female^3", 39, "dance"),
				["dance_dance_26"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_11_v1_male^2", 39, "dance"),
				["dance_dance_27"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_11_v2_male^2", 39, "dance"),
				["dance_dance_28"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_13_v2_female^1", 39, "dance"),
				["dance_dance_29"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_15_v1_male^4", 39, "dance"),
				["dance_dance_30"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_15_v2_female^1", 39, "dance"),
				["dance_dance_31"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@med_intensity", "mi_dance_facedj_15_v2_male^4", 39, "dance"),
				["dance_dance_32"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@med_intensity", "mi_dance_facedj_17_v1_male^4", 39, "dance"),
				["dance_dance_33"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", "trans_dance_facedj_hi_to_li_07_v1_female^6", 39, "dance"),
				["dance_dance_34"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_13_v2_male^4", 39, "dance"),
				["dance_dance_35"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v1_female^6", 39, "dance"),
				["dance_dance_36"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_female^3", 39, "dance"),
				["dance_dance_37"] = new AnimationConfig("anim@mp_player_intupperthe_woogie", "idle_a", 39, "dance"),
				["dance_dance_38"] = new AnimationConfig("anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "med_center_down", 39, "dance"),
				["dance_dance_39"] = new AnimationConfig("anim@mp_player_intupperbanging_tunes", "idle_a", 39, "dance"),
				["dance_dance_40"] = new AnimationConfig("anim@mp_player_intupperbanging_tunes_left", "idle_a", 39, "dance"),
				["dance_dance_41"] = new AnimationConfig("anim@mp_player_intupperbanging_tunes_right", "idle_a", 39, "dance"),
				["dance_dance_42"] = new AnimationConfig("anim@mp_player_intuppercats_cradle", "idle_a", 39, "dance"),
				["dance_dance_43"] = new AnimationConfig("anim@mp_player_intupperdj", "idle_a", 39, "dance"),
				["dance_dance_44"] = new AnimationConfig("anim@mp_player_intupperheart_pumping", "idle_a", 39, "dance"),
				["dance_dance_45"] = new AnimationConfig("anim@mp_player_intupperraise_the_roof", "idle_a", 39, "dance"),
				["dance_dance_46"] = new AnimationConfig("anim@mp_player_intuppersalsa_roll", "idle_a", 39, "dance"),
				["dance_dance_47"] = new AnimationConfig("anim@mp_player_intupperoh_snap", "idle_a", 39, "dance"),
				["dance_dance_48"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_female^1", 39, "dance"),
				["dance_dance_49"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_female^2", 39, "dance"),
				["dance_dance_50"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_female^3", 39, "dance"),
				["dance_dance_51"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_female^6", 39, "dance"),
				["dance_dance_52"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_male^2", 39, "dance"),
				["dance_dance_53"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_male^4", 39, "dance"),
				["dance_dance_54"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^2", 39, "dance"),
				["dance_dance_55"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^4", 39, "dance"),
				["dance_dance_56"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_male^1", 39, "dance"),
				["dance_dance_57"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_male^3", 39, "dance"),
				["dance_dance_58"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_male^6", 39, "dance"),
				["dance_dance_59"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_female^1", 39, "dance"),
				["dance_dance_60"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_female^2", 39, "dance"),
				["dance_dance_61"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_female^3", 39, "dance"),
				["dance_dance_62"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_female^4", 39, "dance"),
				["dance_dance_63"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_female^5", 39, "dance"),
				["dance_dance_64"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_female^6", 39, "dance"),
				["dance_dance_65"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_male^1", 39, "dance"),
				["dance_dance_66"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_male^2", 39, "dance"),
				["dance_dance_67"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_male^3", 39, "dance"),
				["dance_dance_68"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_male^4", 39, "dance"),
				["dance_dance_69"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_male^5", 39, "dance"),
				["dance_dance_70"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_male^6", 39, "dance"),
				["dance_dance_71"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_female^1", 39, "dance"),
				["dance_dance_72"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_female^2", 39, "dance"),
				["dance_dance_73"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_female^3", 39, "dance"),
				["dance_dance_74"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_female^4", 39, "dance"),
				["dance_dance_75"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_female^5", 39, "dance"),
				["dance_dance_76"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_female^6", 39, "dance"),
				["dance_dance_77"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_male^1", 39, "dance"),
				["dance_dance_78"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_male^2", 39, "dance"),
				["dance_dance_79"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_male^3", 39, "dance"),
				["dance_dance_80"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_male^4", 39, "dance"),
				["dance_dance_81"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_male^5", 39, "dance"),
				["dance_dance_82"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_male^6", 39, "dance"),
				["dance_dance_83"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_female^1", 39, "dance"),
				["dance_dance_84"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_female^2", 39, "dance"),
				["dance_dance_85"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_female^3", 39, "dance"),
				["dance_dance_86"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_female^4", 39, "dance"),
				["dance_dance_87"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_female^5", 39, "dance"),
				["dance_dance_88"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_female^6", 39, "dance"),
				["dance_dance_89"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_male^1", 39, "dance"),
				["dance_dance_90"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_male^2", 39, "dance"),
				["dance_dance_91"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_male^3", 39, "dance"),
				["dance_dance_92"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_male^4", 39, "dance"),
				["dance_dance_93"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_male^5", 39, "dance"),
				["dance_dance_94"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_male^6", 39, "dance"),
				["dance_dance_95"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^1", 39, "dance"),
				["dance_dance_96"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^2", 39, "dance"),
				["dance_dance_97"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^3", 39, "dance"),
				["dance_dance_98"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^4", 39, "dance"),
				["dance_dance_99"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^5", 39, "dance"),
				["dance_dance_100"] = new AnimationConfig("anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^6", 39, "dance"),

				["gaits_1"] = new AnimationConfig(null, null, 0, "gaits"),
				["gaits_2"] = new AnimationConfig(null, null, 0, "gaits"),
				["gaits_3"] = new AnimationConfig(null, null, 0, "gaits"),
				["gaits_4"] = new AnimationConfig(null, null, 0, "gaits"),
				["gaits_5"] = new AnimationConfig(null, null, 0, "gaits"),
				["gaits_6"] = new AnimationConfig(null, null, 0, "gaits"),
				["gaits_7"] = new AnimationConfig(null, null, 0, "gaits"),
				["gaits_8"] = new AnimationConfig(null, null, 0, "gaits"),

				["moods_0"] = new AnimationConfig(null, null, 0, "moods"),
				["moods_1"] = new AnimationConfig(null, null, 0, "moods"),
				["moods_2"] = new AnimationConfig(null, null, 0, "moods"),
				["moods_3"] = new AnimationConfig(null, null, 0, "moods"),
				["moods_4"] = new AnimationConfig(null, null, 0, "moods"),
				["moods_5"] = new AnimationConfig(null, null, 0, "moods"),
				["moods_6"] = new AnimationConfig(null, null, 0, "moods"),

				["sit_1"] = new AnimationConfig("amb@medic@standing@tendtodead@base", "base", 39, "sit"),
				["sit_2"] = new AnimationConfig("amb@world_human_stupor@male@base", "base", 39, "sit"),
				["sit_3"] = new AnimationConfig("amb@world_human_sunbathe@male@back@base", "base", 39, "sit"),
				["sit_4"] = new AnimationConfig("missfinale_c1@", "lying_dead_player0", 39, "sit"),
				["sit_5"] = new AnimationConfig("amb@medic@standing@kneel@base", "base", 39, "sit"),
				["sit_6"] = new AnimationConfig("mp_safehouse", "lap_dance_player", 39, "sit"),
				["sit_7"] = new AnimationConfig("misstrevor2", "gang_chatting_idle02_a", 39, "sit"),
				["sit_8"] = new AnimationConfig("amb@lo_res_idles@", "world_human_picnic_male_lo_res_base", 39, "sit"),
				["sit_9"] = new AnimationConfig("anim@amb@business@bgen@bgen_no_work@", "sit_phone_phoneputdown_sleeping_nowork", 39, "sit"),
				["sit_10"] = new AnimationConfig("anim@amb@nightclub@lazlow@lo_alone@", "lowalone_dlg_ughunbelievable_laz", 39, "sit"),
				["sit_11"] = new AnimationConfig("amb@lo_res_idles@", "world_human_bum_slumped_left_lo_res_base", 39, "sit"),
				["sit_12"] = new AnimationConfig("amb@world_human_sunbathe@female@back@base", "base", 39, "sit"),
				["sit_13"] = new AnimationConfig("amb@world_human_sunbathe@male@front@base", "base", 39, "sit"),
				["sit_14"] = new AnimationConfig("amb@lo_res_idles@", "world_human_sit_ups_lo_res_base", 39, "sit"),
				["sit_15"] = new AnimationConfig("amb@world_human_picnic@female@base", "base", 39, "sit"),
			};

			Animations = new ReadOnlyDictionary<string, AnimationConfig>(animDict);
        }

        public static readonly ReadOnlyDictionary<string, AnimationConfig> Animations;
    }

    internal class AnimationConfig
    {
        public string Dictionary { get; set; }
        public string Name { get; set; }
        public int Flag { get; set; }
        public string Category { get; set; }

        public AnimationConfig(string dictionary, string name, int flag, string category)
        {
            Dictionary = dictionary;
            Name = name;
            Flag = flag;
            Category = category;
        }
    }
}
